apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: WORDPRESS_DB_NAME
                name: proyecto
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                key: WORDPRESS_DB_USER
                name: proyecto
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: MYSQL_RANDOM_ROOT_PASSWORD
                name: proyecto
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: WORDPRESS_DB_PASSWORD
                name: proyecto
        volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-pvc
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql
